name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Get packer
      run: |
        wget https://releases.hashicorp.com/packer/1.4.4/packer_1.4.4_linux_amd64.zip
        unzip packer_1.4.4_linux_amd64.zip
        mv packer /usr/local/bin
        chmod 755 /usr/local/bin/packer
    - name: Add user variables
      run: echo ${{ secrets.USER_JSON }} > user.json
    - name: Build
      run: packer build -var-file user.json openvidu.json
